import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const nunitoSans = Nunito_Sans();

export const metadata: Metadata = {
  title: {
    default: "KotaniPay",
    template: "KotaniPay | %s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ToastContainer />
      <body className={nunitoSans.className}>{children}</body>
    </html>
  );
}
